module.exports = {
  content: {
    components: [
      {
        title: 'Web Development',
        image: './images/web.png',
        imageAlt: 'Web Development',
        examples: [
          'React',
          'Vue',
          'SCSS',
          'Javascript',
          'Node.js',
          'React Native',
        ],
      },
      {
        title: 'Unity / VR / AR',
        image: './images/games.png',
        imageAlt: 'Unity',
        examples: [
          'Unity',
          'C#',
          'Vuforia',
          'Unity VR',
        ],
      },
      {
        title: 'Embedded Systems / Maker',
        image: './images/embedded.png',
        imageAlt: 'Embedded Systems',
        examples: [
          'C',
          'NRF/ESP Chips',
          'Arduino',
          'Raspberry Pi',
          'Basic Circuit Design',
        ],
      },
    ],
    projects: [
      {
        title: 'Computer Vision Product Demo',
        description: 'The public demo for the Watson Visual Recognition Service, built in React',
        role: 'Development Lead',
        image: './images/vr.png',
        imageAlt: 'Computer Vision Product Demo',
        link: 'https://watson-visual-recognition-duo-dev.ng.bluemix.net/',
      },
      {
        title: 'Watson Chatbot Product Demo',
        description: 'The public demo for the Watson Assistant Service, built in React',
        role: 'Development Lead',
        image: './images/chatbot.png',
        imageAlt: 'Watson Chatbot Product Demo',
        link: 'https://watson-conversation-duo-dev.ng.bluemix.net/',
      },
      {
        title: 'Watson Website',
        description: 'The main website for the Watson business unit. Contributed content and front end development. Built in Pug',
        role: 'Contributing Developer',
        image: './images/website.png',
        imageAlt: 'Computer Vision Product Demo',
        link: 'https://www.ibm.com/watson/',
      },
      {
        title: 'Watson React Component Library',
        description: 'A shared internal component library used for Watson product demos, built in React',
        role: 'Development Lead',
        image: './images/component.png',
        imageAlt: 'Computer Vision Product Demo',
      },
      {
        title: '"Channel" - 2018 Global Jam Game',
        description: 'A VR game, built in Unity, that has the player play as a ghost and navigate through a room, searching for clues about their past life',
        role: 'C# Developer',
        image: './images/channel.png',
        imageAlt: 'Computer Vision Product Demo',
      },
      {
        title: 'Embedded System Tabletop Game',
        description: 'A board game that runs on NRF and AVR chips, where players move pieces and use abilities through a React Native Mobile app',
        role: 'Personal Project',
        image: './images/board.png',
        imageAlt: 'Computer Vision Product Demo',
        link: 'https://github.com/Repjarms/digital-game-board',
      },
    ],
    footerLinks: [
      {
        title: 'Email',
        image: './images/email.png',
        imageAlt: 'Email',
        link: 'mailto:jeffarn12@gmail.com',
      },
      {
        title: 'Github',
        image: './images/github.png',
        imageAlt: 'Github',
        link: 'https://github.com/Repjarms',
      },
      {
        title: 'Codepen',
        image: './images/codepen.png',
        imageAlt: 'Codepen',
        link: 'https://codepen.io/Repjarms/',
      },
    ],
  },
};
